---

# ====================================================================================================================================

- name: INFORMATION
  hosts: all

  vars:
    - ansible_deployer: "{{ lookup('env','ANSIBLE_DEPLOYER') }}"
    - artifacts: "{{ lookup('env','ARTIFACTS') }}"

# ------------------------------------------------------------------------------------------------------------------------------------

  become: yes
  become_user: "root"
  
# ====================================================================================================================================

  tasks:

# ------------------------------------------------------------------------------------------------------------------------------------


    - name: Host Information
      debug:
        msg: 
          - "User:          {{ ansible_user }}"        
          - "Hostname:      {{ ansible_hostname }}"
          - "Distribution:  {{ ansible_distribution }}"
          - "Major Version: {{ ansible_distribution_major_version }}"
          - "Version:       {{ ansible_distribution_version }}"
      when: 
        # - ansible_distribution != "CentOS" and ansible_distribution != "OracleLinux"
        # - ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux"
        # - ansible_distribution == "CentOS"
        # - ansible_distribution == "OracleLinux"
        # - ansible_distribution == "Ubuntu"
        # - ansible_distribution_version < '7'
        # - ansible_distribution_major_version == '6'

# ====================================================================================================================================


