---

# ====================================================================================================================================

- name: WINSTRAP
  hosts: localhost

  vars:
    - ansible_deployer: "{{ lookup('env','ANSIBLE_DEPLOYER') }}"
    - artifacts: "{{ lookup('env','ARTIFACTS') }}"
    - home_win: "{{ lookup('env','HOME_WIN') }}"

# ------------------------------------------------------------------------------------------------------------------------------------

  become: yes
  become_user: "{{ ansible_deployer }}"
  
# ====================================================================================================================================

  tasks:

# ====================================================================================================================================

    - name: Create Directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ home_win }}/.ssh"
        - "{{ home_win }}/VirtualBox"

# ------------------------------------------------------------------------------------------------------------------------------------

    # - name: Copy SSH Config
    #   copy: 
    #     src: "{{ item }}"
    #     dest: "{{ home_win }}/.ssh/"
    #     mode: "0644"
    #   with_items:
    #     - "{{ artifacts }}/home/user/.ssh/authorized_keys"
    #     - "{{ artifacts }}/home/user/.ssh/config"

    - name: Copy SSH Public
      copy: 
        src: "{{ item }}"
        dest: "{{ home_win }}/.ssh/"
        mode: "0644"
      with_fileglob:
        - "{{ artifacts }}/home/user/.ssh/*.pub"

    - name: Copy SSH Private
      copy: 
        src: "{{ item }}"
        dest: "{{ home_win }}/.ssh/"
        mode: "0600"
      with_fileglob:
        - "{{ artifacts }}/home/user/.ssh/*.key"
        - "{{ artifacts }}/home/user/.ssh/*.pem"
        - "{{ artifacts }}/home/user/.ssh/*.ppk"

# ------------------------------------------------------------------------------------------------------------------------------------

    # - name: Copy GnuPG
    #   copy: 
    #     src: "{{ item }}"
    #     dest: "{{ home_win }}/.gnupg/"
    #     mode: "preserve"
    #   with_fileglob:
    #     - "{{ artifacts }}/home/user/.gnupg/"

# ------------------------------------------------------------------------------------------------------------------------------------

    # - name: Copy Config Files
    #   copy: 
    #     src: "{{ item }}"
    #     dest: "{{ home_win }}/"
    #     mode: "preserve"
    #   with_fileglob:
    #     - "{{ artifacts }}/home/user/.gitconfig"
    #     - "{{ artifacts }}/home/user/settings.json"

    # - name: Copy Config Directories
    #   copy: 
    #     src: "{{ item }}"
    #     dest: "{{ home_win }}/"
    #     mode: "preserve"
    #   with_items:
    #     - "{{ artifacts }}/home/user/.gnupg"
    #     - "{{ artifacts }}/home/user/Desktop"


# ====================================================================================================================================

    # - name: Create Directory
    #   file:
    #     path: "{{ item }}"
    #     state: directory
    #   with_items:
    #     - "/mnt/c/Commands"
    #     - "/mnt/c/totalcmd"

# ------------------------------------------------------------------------------------------------------------------------------------

    # - name: Copy Commands
    #   copy: 
    #     src: "{{ artifacts }}/Local/Commands/"
    #     dest: "/mnt/c/Commands/"
    #     mode: "preserve"

# ------------------------------------------------------------------------------------------------------------------------------------

    # - name: Copy Totalcmd
    #   copy: 
    #     src: "{{ artifacts }}/Local/totalcmd/"
    #     dest: "/mnt/c/totalcmd/"
    #     mode: "preserve"

# ====================================================================================================================================
