#!/bin/bash

#===BASE====================================================================================================================

MYNAME=$0
BASENAME=$(basename $MYNAME)
INSTANCE_PATH="/mnt/c/Users/$USER/Work/spaces/labspace/vagrant"

if [ -x /usr/bin/figlet ]; then
    ECHO="/usr/bin/figlet"
else
    ECHO="/bin/echo"
fi

# $ECHO $BASENAME

#===FUNCTIONS===============================================================================================================

function vgr_instance_list () {
    echo ""
    echo "Instance List"
    echo "--------------------------------------"
    for i in $(ls -l "$INSTANCE_PATH" | awk '{print $9}'); do
        INSTANCE_STATUS="$(VBoxManage.exe showvminfo $i 2>/dev/null | grep "State" | cut -d "(" -f 1 | awk '{print $2" "$3}')"
        [ -d "$i" ] && [ "$i" != "commands" ] &&  echo " $i" $'\t' "$INSTANCE_STATUS"
    done
    echo "--------------------------------------"
    echo "Usage: $BASENAME [action] | list [host]"
    echo ""
}

function vgr_instance_actions_list () {
    ls "$INSTANCE_PATH/$INSTANCE_NAME" | grep sh | grep -v environment | cut -d "." -f 1 
}

function vgr_instance () {
    INSTANCE_ACTION_LIST="$(vgr_instance_actions_list)"
    for a in $INSTANCE_ACTION_LIST; do
        [ "$a" == "$INSTANCE_ACTION" ] && INSTANCE_ACTION_EXISTS="true"
    done
    if [ "$INSTANCE_ACTION_EXISTS" ]; then
        $INSTANCE_PATH/$INSTANCE_NAME/$INSTANCE_ACTION.sh 2>/dev/null
    else
        echo ""
        echo "Instance \"$INSTANCE_NAME\" Actions"
        echo "--------------------------------------"
        vgr_instance_actions_list
        echo "--------------------------------------"
        echo ""
    fi
}

#===ACTIONS=================================================================================================================


cd "$INSTANCE_PATH"

INSTANCE_NAME="$2"
INSTANCE_ACTION="$1"

case  $1 in
    "")
        vgr_instance_list
        ;;
    list)
        vgr_instance_list
        ;;
    *)
        vgr_instance $INSTANCE_ACTION $INSTANCE_NAME
        ;;
esac

#===========================================================================================================================
