---

# ====================================================================================================================================

- name: UPDATING
  hosts: localhost
  
  vars:
    - ansible_deployer: "{{ lookup('env','ANSIBLE_DEPLOYER') }}"
    - artifacts: "{{ lookup('env','ARTIFACTS') }}"

# ------------------------------------------------------------------------------------------------------------------------------------

  become: yes
  become_user: root
  
# ====================================================================================================================================

  tasks:

# ====================================================================================================================================

    - name: Update
      apt: 
        update_cache: yes

    - name: Upgrade
      apt:
        upgrade: dist

# ====================================================================================================================================

