name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
# Set the job key. The key is displayed as the job name
# when a job name is not provided
  test:
    # Name the Job
    name: Molecule
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        
      - name: Run build script
        run: sudo ./.github/scripts/ping-slack.sh
        shell: bash
