name: CI
on:
  issue_comment:
    types:
      - created
  push:
    branches:
      - main

jobs:
# Set the job key. The key is displayed as the job name
# when a job name is not provided
  Ping_Slack:
    # Name the Job
    name: Ping_Slack
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request 
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      
      - run: |
          echo "$ENV_MESSAGE" "$ENV_SLACK_WEBHOOK"
        
      - name: Run build script
        run: ./.github/scripts/ping-slack.sh
        shell: bash
        env:
          ENV_SLACK_WEBHOOK:  ${{secrets.SLACK_WEBHOOK }}
          ENV_MESSAGE: ${{ github.event.comment.body }}
